# this Ansible playbook to update the hosts file from my GitHub repo
---
- hosts: pies
  become: yes
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Run the equivalent of "apt-get upgrade" as a separate step
      apt:
        name: "*"
        state: latest
